services:
  - type: web
    name: fileqa-rag-chatbot
    runtime: docker
    repo: https://github.com/udhaykarthiik/fileQA-RAG
    plan: free
    healthCheckPath: /healthz
    healthCheckTimeout: 300
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: PYTHONUNBUFFERED
        value: "1"