services:
  - type: web
    name: fileqa-rag-chatbot
    runtime: docker
    repo: https://github.com/udhaykarthiik/fileQA-RAG
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
      - key: FASTEMBED_CACHE_PATH
        value: "/tmp/fastembed_cache"